-- Table: _flms.coaches

-- DROP TABLE IF EXISTS _flms.coaches;

CREATE TABLE IF NOT EXISTS _flms.coaches
(
    coach_name character varying COLLATE pg_catalog."default" NOT NULL,
    nationality character varying COLLATE pg_catalog."default",
    coach_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date_of_birth date,
    CONSTRAINT coaches_pkey PRIMARY KEY (coach_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS _flms.coaches
    OWNER to postgres;
-- Index: idx_coach_name

-- DROP INDEX IF EXISTS _flms.idx_coach_name;

CREATE INDEX IF NOT EXISTS idx_coach_name
    ON _flms.coaches USING btree
    (coach_name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;